import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#004d46',
        'surface-tint': '#2b6954',
        'surface-variant': '#d3e4fe',
        'tertiary-fixed': '#89f5e7',
        'surface-dim': '#cbdbf5',
        'on-surface-variant': '#404944',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#0b513d',
        'primary-container': '#064e3b',
        'on-primary': '#ffffff',
        background: '#f8f9ff',
        surface: '#f8f9ff',
        primary: '#003527',
        'on-secondary-container': '#fefcff',
        'on-primary-container': '#80bea6',
        secondary: '#0051d5',
        'secondary-container': '#316bf3',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-container': '#53c2b5',
        'on-tertiary-fixed-variant': '#005049',
        tertiary: '#00342f',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#213145',
        outline: '#707974',
        'on-background': '#0b1c30',
        'primary-fixed-dim': '#95d3ba',
        'on-primary-fixed': '#002117',
        'secondary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#00174b',
        'primary-fixed': '#b0f0d6',
        'surface-container': '#e5eeff',
        'on-error': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container-highest': '#d3e4fe',
        'outline-variant': '#bfc9c3',
        'inverse-on-surface': '#eaf1ff',
        'on-error-container': '#93000a',
        'on-surface': '#0b1c30',
        'secondary-fixed': '#dbe1ff',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'tertiary-fixed-dim': '#6bd8cb',
        'inverse-primary': '#95d3ba',
        'on-secondary-fixed-variant': '#003ea8',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        lg: '40px',
        base: '8px',
        xl: '64px',
        sm: '12px',
        md: '24px',
        'container-max': '1280px',
        'touch-target': '48px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'data-display': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'data-display': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg': [
          '28px',
          { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      boxShadow: {
        card: '0 4px 15px rgba(6, 78, 59, 0.05)',
        'card-lg': '0 4px 20px rgba(6, 78, 59, 0.08)',
        'card-xl': '0 8px 30px rgba(0, 53, 39, 0.04)',
        elevated: '0 12px 40px rgba(0, 53, 39, 0.15)',
        'top-nav': '0 2px 10px rgba(0, 53, 39, 0.05)',
        'bottom-nav': '0 -4px 15px rgba(6, 78, 59, 0.05)',
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config;
