import type {
  BOMLineItem,
  OtherScopeItem,
  ScenarioTemplate,
  SyncType,
} from '@/types';
import { uid } from '../uid';

/**
 * Hand-derived from `docs/Project costing details _MW.xlsx`. The 1 MW HT-Sync
 * sheet drives the canonical values; the 700 kW LT sheet drops HT switchyard
 * gear and swaps the approvals item. Keeping seed ids stable so the editor's
 * "duplicate" affordance and any future migration can reference them.
 */

let seq = 0;
function nextSeq(): number {
  seq += 1;
  return seq;
}

function resetSeq() {
  seq = 0;
}

function bomLine(args: Omit<BOMLineItem, 'id' | 'sequence'>): BOMLineItem {
  return {
    id: `bom_${uid('ln')}`,
    sequence: nextSeq(),
    ...args,
  };
}

function scopeItem(args: Omit<OtherScopeItem, 'id' | 'sequence'>): OtherScopeItem {
  return {
    id: `scp_${uid('sc')}`,
    sequence: nextSeq(),
    ...args,
  };
}

/* ------------------------------------------------------------------------ */
/* Reusable line builders — one helper per item that recurs across templates */
/* ------------------------------------------------------------------------ */

function htMainBom(): BOMLineItem[] {
  resetSeq();
  return [
    bomLine({
      category: 'modules',
      itemName: 'Solar PV Module 540 Wp',
      description:
        'Solar PV Module — Mono-PERC, 540 Wp, half-cut bifacial. Make: APS / Premier / N Icon.',
      make: 'APS / Premier / N Icon',
      uom: 'count',
      baseQuantity: 1852,
      rate: 7290,
      gstPercent: 12,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'inverters',
      itemName: 'String Inverter 250 kW',
      description:
        'Grid-connect solar inverter, 1 × 250 kW, 800 V AC, MPPT, DC:AC ≤ 1.5.',
      make: 'Solis / APS / Polycab',
      uom: 'count',
      baseQuantity: 1,
      rate: 410000,
      gstPercent: 12,
      scalingType: 'step',
      unitCapacityKW: 250,
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '1C × 6 sq.mm Cu Solar DC Cable',
      description: 'Array → string → inverter DC cable run.',
      make: 'Polycab / Lapp',
      uom: 'meter',
      baseQuantity: 10000,
      rate: 52,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '3C × 150 sq.mm AC Armoured Cable',
      description: 'XLPE armoured Al PVC 1.1 kV FR cable.',
      make: 'Polycab / Universal',
      uom: 'meter',
      baseQuantity: 500,
      rate: 680,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '3C × 300 sq.mm AC Armoured Cable',
      description: 'XLPE armoured Al PVC 1.1 kV FR cable for inverter trunks.',
      make: 'Polycab / Universal',
      uom: 'meter',
      baseQuantity: 60,
      rate: 1250,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '1C × 16 sq.mm Cu LA Earth Cable',
      description: '1.1 kV FR flexible Cu cable for lightning-arrestor earthing.',
      make: 'Polycab / Universal',
      uom: 'meter',
      baseQuantity: 60,
      rate: 300,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'mounting',
      itemName: 'Module Mounting Structure (28 MMS)',
      description:
        'Galvanised penetrating-type 28 MMS mounting structure (kg of steel).',
      make: 'Galvanized',
      uom: 'kg',
      baseQuantity: 25000,
      rate: 100,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'mounting',
      itemName: 'Inverter Mounting Structure with Canopy',
      description: 'One canopy structure per inverter block.',
      uom: 'count',
      baseQuantity: 1,
      rate: 8000,
      gstPercent: 18,
      scalingType: 'step',
      unitCapacityKW: 250,
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Lightning Arrestor (ESE)',
      description: 'ESE / conventional with counter (Mytrah / Torq).',
      make: 'Torq',
      uom: 'count',
      baseQuantity: 2,
      rate: 32000,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Earthing Kit (Cu-bonded)',
      description:
        '40 mm dia × 2 m copper-bonded maintenance-free electrode kit.',
      uom: 'meter',
      baseQuantity: 18,
      rate: 3000,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Earthing Strip GI 25 × 3 mm',
      description: 'Hot-dip GI strip (kg).',
      make: 'Hot Dip',
      uom: 'kg',
      baseQuantity: 1500,
      rate: 82,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Earthing Strip GI 50 × 6 mm (HT grade)',
      description: 'HT-grade earth-pit grid GI strip (kg).',
      uom: 'kg',
      baseQuantity: 500,
      rate: 150,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'metering',
      itemName: 'Inverter Termination Box (DCDB)',
      description: 'One DCDB per inverter block.',
      uom: 'count',
      baseQuantity: 1,
      rate: 55000,
      gstPercent: 18,
      scalingType: 'step',
      unitCapacityKW: 250,
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'metering',
      itemName: '4-IN-1-OUT AC LTDB / ACB',
      description:
        '250A 4P MCCB & 1000A ACB with metering, SPD, breakers.',
      make: 'L&T / Schneider / Siemens',
      uom: 'count',
      baseQuantity: 1,
      rate: 500000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'monitoring',
      itemName: 'Weather Monitoring System',
      description: 'On-site WMS with data logger.',
      uom: 'count',
      baseQuantity: 1,
      rate: 100000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'monitoring',
      itemName: 'SCADA',
      description: 'Plant-wide SCADA control + monitoring.',
      uom: 'count',
      baseQuantity: 1,
      rate: 200000,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'switchyard',
      itemName: 'Step-Up Power Transformer 1200 kVA',
      description: '0.80 / 33 kV oil-cooled step-up transformer.',
      make: 'Esennar',
      uom: 'count',
      baseQuantity: 1,
      rate: 1600000,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'switchyard',
      itemName: 'VCB Panel 33 kV',
      description: 'VCB panel with metering & protection control.',
      make: 'CG / ABB',
      uom: 'count',
      baseQuantity: 1,
      rate: 700000,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'switchyard',
      itemName: 'HT Switch Yard',
      description: 'HT switchyard erection.',
      uom: 'count',
      baseQuantity: 1,
      rate: 500000,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'services',
      itemName: 'Installation & Commissioning + Civil',
      description: 'EPC labour + civil work, ₹/Wp.',
      uom: 'Wp',
      baseQuantity: 1_000_000,
      rate: 2.75,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'services',
      itemName: 'Design & Engineering',
      description: 'Detailed engineering + drawings, ₹/Wp.',
      uom: 'Wp',
      baseQuantity: 1_000_000,
      rate: 0.20,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'services',
      itemName: 'Approvals (HT)',
      description: 'NREDCAP / DISCOM / SLDC + synchronisation, HT.',
      uom: 'Wp',
      baseQuantity: 1_000_000,
      rate: 1.0,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'civil',
      itemName: 'DWC Pipe (UV-protected)',
      description: 'DWC piping, m.',
      uom: 'meter',
      baseQuantity: 1600,
      rate: 45,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'civil',
      itemName: 'Inverter Stands & ACDB Platform',
      description: 'Concrete stands + ACDB mounting platform.',
      uom: 'lot',
      baseQuantity: 1,
      rate: 50000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'logistics',
      itemName: 'Transport & Storage',
      description: 'Inbound + onsite logistics.',
      uom: 'lot',
      baseQuantity: 1,
      rate: 100000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'misc',
      itemName: 'Hardware Misc',
      description: 'Fasteners, lugs, glands, etc.',
      uom: 'lot',
      baseQuantity: 1,
      rate: 200000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
  ];
}

function htOtherScope(): OtherScopeItem[] {
  resetSeq();
  return [
    scopeItem({
      scopeName: 'CEIG Inspection & Approval Fee',
      baseAmount: 130000,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['HT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    scopeItem({
      scopeName: 'Module Cleaning System',
      baseAmount: 70000,
      gstPercent: 18,
      scalingType: 'optional',
      isOptional: true,
      includedByDefault: false,
    }),
    scopeItem({
      scopeName: 'Shed for Inverter & ACDB',
      baseAmount: 35000,
      gstPercent: 18,
      scalingType: 'optional',
      isOptional: true,
      includedByDefault: false,
    }),
    scopeItem({
      scopeName: 'RS-485 Communication Cable & Accessories',
      baseAmount: 50000,
      gstPercent: 18,
      scalingType: 'optional',
      isOptional: true,
      includedByDefault: false,
    }),
  ];
}

function ltMainBom(): BOMLineItem[] {
  resetSeq();
  // 700 kW LT plant — derived from the 1 MW sheet by scaling base quantities
  // pro-rata at 0.7 ratio for linear items, dropping HT switchyard gear, and
  // swapping the Approvals service to its LT variant.
  const ratio = 0.7;
  const lin = (n: number) => Math.round(n * ratio);

  return [
    bomLine({
      category: 'modules',
      itemName: 'Solar PV Module 540 Wp',
      description:
        'Solar PV Module — Mono-PERC, 540 Wp. Make: APS / Premier / N Icon.',
      make: 'APS / Premier / N Icon',
      uom: 'count',
      baseQuantity: lin(1852),
      rate: 7290,
      gstPercent: 12,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'inverters',
      itemName: 'String Inverter 250 kW',
      description:
        'Grid-connect solar inverter, 1 × 250 kW, 800 V AC, MPPT, DC:AC ≤ 1.5.',
      make: 'Solis / APS / Polycab',
      uom: 'count',
      baseQuantity: 1,
      rate: 410000,
      gstPercent: 12,
      scalingType: 'step',
      unitCapacityKW: 250,
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '1C × 6 sq.mm Cu Solar DC Cable',
      description: 'Array → string → inverter DC cable run.',
      make: 'Polycab / Lapp',
      uom: 'meter',
      baseQuantity: lin(10000),
      rate: 52,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '3C × 150 sq.mm AC Armoured Cable',
      description: 'XLPE armoured Al PVC 1.1 kV FR cable.',
      make: 'Polycab / Universal',
      uom: 'meter',
      baseQuantity: lin(500),
      rate: 680,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'cables',
      itemName: '1C × 16 sq.mm Cu LA Earth Cable',
      description: '1.1 kV FR flexible Cu cable for lightning-arrestor earthing.',
      make: 'Polycab / Universal',
      uom: 'meter',
      baseQuantity: lin(60),
      rate: 300,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'mounting',
      itemName: 'Module Mounting Structure (28 MMS)',
      description: 'Galvanised penetrating-type 28 MMS mounting structure (kg).',
      make: 'Galvanized',
      uom: 'kg',
      baseQuantity: lin(25000),
      rate: 100,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'mounting',
      itemName: 'Inverter Mounting Structure with Canopy',
      description: 'One canopy structure per inverter block.',
      uom: 'count',
      baseQuantity: 1,
      rate: 8000,
      gstPercent: 18,
      scalingType: 'step',
      unitCapacityKW: 250,
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Lightning Arrestor (ESE)',
      description: 'ESE / conventional with counter.',
      make: 'Torq',
      uom: 'count',
      baseQuantity: 2,
      rate: 32000,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Earthing Kit (Cu-bonded)',
      description: '40 mm dia × 2 m copper-bonded maintenance-free electrode kit.',
      uom: 'meter',
      baseQuantity: lin(18),
      rate: 3000,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'earthing',
      itemName: 'Earthing Strip GI 25 × 3 mm',
      description: 'Hot-dip GI strip (kg).',
      make: 'Hot Dip',
      uom: 'kg',
      baseQuantity: lin(1500),
      rate: 82,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'metering',
      itemName: 'Inverter Termination Box (DCDB)',
      description: 'One DCDB per inverter block.',
      uom: 'count',
      baseQuantity: 1,
      rate: 55000,
      gstPercent: 18,
      scalingType: 'step',
      unitCapacityKW: 250,
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'metering',
      itemName: 'AC LTDB / ACB Panel',
      description: 'LT distribution panel with metering, breakers, SPD.',
      make: 'L&T / Schneider / Siemens',
      uom: 'count',
      baseQuantity: 1,
      rate: 350000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'monitoring',
      itemName: 'Weather Monitoring System',
      description: 'On-site WMS with data logger.',
      uom: 'count',
      baseQuantity: 1,
      rate: 100000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'services',
      itemName: 'Installation & Commissioning + Civil',
      description: 'EPC labour + civil work, ₹/Wp.',
      uom: 'Wp',
      baseQuantity: 700_000,
      rate: 2.75,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'services',
      itemName: 'Design & Engineering',
      description: 'Detailed engineering + drawings, ₹/Wp.',
      uom: 'Wp',
      baseQuantity: 700_000,
      rate: 0.20,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'services',
      itemName: 'Approvals (LT)',
      description: 'NREDCAP / DISCOM + synchronisation, LT.',
      uom: 'Wp',
      baseQuantity: 700_000,
      rate: 0.75,
      gstPercent: 18,
      scalingType: 'conditional',
      applicability: { syncTypes: ['LT'] },
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'civil',
      itemName: 'DWC Pipe (UV-protected)',
      description: 'DWC piping, m.',
      uom: 'meter',
      baseQuantity: lin(1600),
      rate: 45,
      gstPercent: 18,
      scalingType: 'linear',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'civil',
      itemName: 'Inverter Stands & ACDB Platform',
      description: 'Concrete stands + ACDB mounting platform.',
      uom: 'lot',
      baseQuantity: 1,
      rate: 50000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'logistics',
      itemName: 'Transport & Storage',
      description: 'Inbound + onsite logistics.',
      uom: 'lot',
      baseQuantity: 1,
      rate: 80000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
    bomLine({
      category: 'misc',
      itemName: 'Hardware Misc',
      description: 'Fasteners, lugs, glands, etc.',
      uom: 'lot',
      baseQuantity: 1,
      rate: 150000,
      gstPercent: 18,
      scalingType: 'fixed',
      isOptional: false,
      includedByDefault: true,
    }),
  ];
}

function ltOtherScope(): OtherScopeItem[] {
  resetSeq();
  return [
    scopeItem({
      scopeName: 'Module Cleaning System',
      baseAmount: 50000,
      gstPercent: 18,
      scalingType: 'optional',
      isOptional: true,
      includedByDefault: false,
    }),
    scopeItem({
      scopeName: 'Shed for Inverter & ACDB',
      baseAmount: 35000,
      gstPercent: 18,
      scalingType: 'optional',
      isOptional: true,
      includedByDefault: false,
    }),
    scopeItem({
      scopeName: 'RS-485 Communication Cable & Accessories',
      baseAmount: 30000,
      gstPercent: 18,
      scalingType: 'optional',
      isOptional: true,
      includedByDefault: false,
    }),
  ];
}

/* ------------------------------------------------------------------------ */
/* Public seed builders                                                      */
/* ------------------------------------------------------------------------ */

function template(args: {
  id: string;
  name: string;
  baseCapacityKW: number;
  syncType: SyncType;
  description: string;
  mainBom: BOMLineItem[];
  otherScope: OtherScopeItem[];
}): ScenarioTemplate {
  const now = Date.now();
  return {
    id: args.id,
    name: args.name,
    projectType: 'utility',
    syncType: args.syncType,
    baseCapacityKW: args.baseCapacityKW,
    status: 'active',
    version: 'v1',
    effectiveFrom: now,
    description: args.description,
    source: 'seed',
    createdAt: now,
    updatedAt: now,
    mainBom: args.mainBom,
    otherScope: args.otherScope,
  };
}

export const SEED_TEMPLATE_ID_HT = 'tpl_seed_1mw_ht';
export const SEED_TEMPLATE_ID_LT = 'tpl_seed_700kw_lt';

export function seedTemplates(): ScenarioTemplate[] {
  return [
    template({
      id: SEED_TEMPLATE_ID_HT,
      name: '1000 KW Ground Mounted - HT Sync',
      baseCapacityKW: 1000,
      syncType: 'HT',
      description:
        'Canonical 1 MW utility-scale ground-mounted plant with HT switchyard, derived from Project costing details _MW.xlsx.',
      mainBom: htMainBom(),
      otherScope: htOtherScope(),
    }),
    template({
      id: SEED_TEMPLATE_ID_LT,
      name: '700 KW Ground Mounted - LT Sync',
      baseCapacityKW: 700,
      syncType: 'LT',
      description:
        'LT-tied 700 kW ground-mounted plant. No step-up transformer / HT switchyard; uses LT approvals stream.',
      mainBom: ltMainBom(),
      otherScope: ltOtherScope(),
    }),
  ];
}
